### ISSUE TITLE
hardnested

### ISSUE THREAD

**Issue by Alfa16bravo** [ElectronicCats/HunterCatNFC#11]
hello, attack nested and hardnested for mifare classic would be possible with the rp2040 and pn7150? THANKS

**Comment by AndreaZGuz** [comment]
Hello @Alfa16bravo !

Thank you for contacting us,
Please, in order to understand your situation better, could you explain to us exactly the test you are trying to execute?
Are you using any of the examples given for Hunter Cat NFC or PN7150 in our repositories?
Which example are you trying to run?

Kind regards,

**Comment by AndreaZGuz** [comment]
Hello @Alfa16bravo 

If you do not have more questions at this moment, we will now close this issue.
Remember you can re-open it if you need further assistance.

Regards!
